version: '3.8'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - "${PORT_NO}:80"
    restart: unless-stopped
    volumes:
      - /var/www/nextcloud:/var/www/html/data
    environment:
      - NEXTCLOUD_ADMIN_USER=${ADMIN_USERNAME}
      - NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN_NAME}
